#!/bin/python3
#day 7 hackerrank solution with python 
import math
import os
import random
import re
import sys


if __name__ == '__main__':
    n = int(input())
    re=""
    arr = list(map(int, input().rstrip().split()))
    array=arr[::-1]
    for i in array:
      re+=str(i)
      re+=" "
    print(re)
 
 #Khaled Helmy
